In [3]:
import numpy as np

# 배열의 index 접근하기

## 1차원 배열의 index 접근

In [11]:
arr = np.arange(10)
print(arr)

print(arr[3])   ## 인덱스 값이 3인 위치의 값
print(arr[1])   ## 인덱스 값이 1인 위치의 값
print(arr[-1])  ## 0번째 인덱스에서 -1의 위치에 있는 값
print(arr[-3])  ## 0번째 인덱스에서 -3의 위치에 있는 값
print(arr[-10]) ## 0번째 인덱스에서 -10의 위치에 있는 값
print(arr[10])  ## 존재하지 않는 인덱스는 에러가 난다!

[0 1 2 3 4 5 6 7 8 9]
3
1
9
7
0


IndexError: index 10 is out of bounds for axis 0 with size 10

## 2차원 배열의 index 접근

In [15]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr, arr.shape, arr.ndim)

print(arr[0])     ## 0행
print(arr[0][0])  ## 0행의 0열
print(arr[1, 2])  ## 1행의 2열 ([x,y]의 형태로 지정해도 된다!)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] (3, 4) 2
[1 2 3 4]
1
7


## 1차원 배열에서의 탐색

In [23]:
arr = np.arange(10)
print(arr[3:8])     ## 3번째 인덱스부터 8번째 인덱스 미만까지의 원소
print(arr[3:])      ## 3번쨰 인덱스부터 마지막 인덱스까지의 원소
print(arr[:7])      ## 0번째 인덱스부터 7번째 인덱스 미만까지의 원소
print(arr[:-1])     ## 마지막 인덱스 미만까지의 모든 원소

[3 4 5 6 7]
[3 4 5 6 7 8 9]
[0 1 2 3 4 5 6]
[0 1 2 3 4 5 6 7 8]


## 2차원 배열에서의 탐색

In [31]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr[0, :])     ## 0번째 행의 모든 원소
print(arr[:, 1])     ## 모든 행의 1번째 인덱스(열)의 원소
print(arr[:3, :])    ## 3 미만의 행까지 모든 (열의) 원소
print(arr[:2, 2:])   ## 2 미만의 행까지의 인덱스 2부터 마지막 인덱스까지의 원소

[1 2 3 4]
[ 2  6 10]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[3 4]
 [7 8]]


# Fancy 인덱싱

## 1차원 배열의 Fancy 인덱싱

In [37]:
# 특정 인덱스 여러 개를 선택해서 탐색

arr = np.arange(5, 31, 5)
print(arr)
print(arr[[0, 2, 4]])     ## 0번째, 2번째, 4번째 원소

[ 5 10 15 20 25 30]
[ 5 15 25]


## 2차원 배열의 Fancy 인덱싱

In [42]:
arr = np.array([[5, 10, 15, 20],
                [25, 30, 35, 40],
                [45, 50, 55, 60]])

print(arr[[0,2], 2:])     ## 0번째, 2번째 행의 2열부터 끝까지의 원소
print(arr[1:, [2, 3]])    ## 1행부터 끝까지의 2, 3열의 원소

[[15 20]
 [55 60]]
[[35 40]
 [55 60]]


# Boolean 인덱싱

## 1차원 배열의 Boolean 인덱싱

In [44]:
# True에 해당하는 값은 출력하고 False에 해당하는 값은 출력하지 않음

arr = np.array([1, 2, 3, 4])
print(arr[[True, False, True, True]])

[1 3 4]


## 2차원 배열의 Boolean 인덱싱

In [49]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr[[True, False], True]) ## 0행은 가져오고 1행은 X + 모든 열 가져옴

[[1 2 3 4]]


## 조건연산자를 이용해서 값 가져오기

In [53]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]])

print(arr[arr > 3])     ## 3보다 큰 모든 원소
print(arr[arr > 4])     ## 4보다 큰 모든 원소
print(arr[arr <= 2])    ## 2 이하의 모든 원소

[4 5 6 7 8]
[5 6 7 8]
[1 2]
