In [1]:
import numpy as np

# 배열의 연산 - 1

In [6]:
# 사칙연산, 제곱, 제곱근, 나머지, 몫

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full_like(arr1, 2)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


## 사칙연산

In [15]:
# 덧셈

print(arr1 + arr2)
print(np.add(arr1, arr2))       ## np 모듈의 add() 함수를 사용

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [16]:
# 뺄셈

print(arr1 - arr2)
print(np.subtract(arr1, arr2))  ## np 모듈의 subtract() 함수를 사용

[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]


In [17]:
# 곱셈 (원소 단위의 곱셈의 결과 출력!)

print(arr1 * arr2)
print(np.multiply(arr1, arr2))  ## np 모듈의 multiply() 함수 사용

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [18]:
# 나눗셈

print(arr1 / arr2)
print(np.divide(arr1, arr2))    ## np 모듈의 divide() 함수 사용

[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]


## 제곱과 제곱근

In [26]:
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9]])
arr2 = np.full_like(arr1, 2)

print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[2 2 2]
 [2 2 2]
 [2 2 2]]


In [28]:
# 제곱

print(arr1 ** 2)
print(np.square(arr1))     ## np 모듈의 square() 함수로 자기 자신을 제곱한 값 출력

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [31]:
# 제곱근

print(np.sqrt(arr1))   ## np 모듈의 sqrt() 함수 사용 --> sqrt = square root

[[1.         1.41421356 1.73205081]
 [2.         2.23606798 2.44948974]
 [2.64575131 2.82842712 3.        ]]


## 몫과 나머지

In [33]:
# 몫

print(arr1 // 2)


# 나머지

print(arr1 % 2)

[[0 1 1]
 [2 2 3]
 [3 4 4]]
[[1 0 1]
 [0 1 0]
 [1 0 1]]


# 배열의 연산 - 2

## 내적 연산 (dot product)

In [43]:
# np.dot()
##두 벡터(행렬)을 곱했을 때 결과값이 스칼라..? 값이 나오는 것

### 1차원 행렬의 내적 연산

In [40]:
arr1 = np.array([2, 3, 4])
arr2 = np.array([1, 2, 3])

print(np.dot(arr1, arr2))   ## 2*1 + 3*2 + 4*3

20


### 2차원 행렬의 내적 연산

In [41]:
'''
[[a, b]      [[e, f]            [[ae + bg, af + bh]
 [c, d]]      [g, h]]    =>      [ce + dg, cf + dh]]
'''

arr1 = np.array([[1, 2],
                 [4, 5]])
arr2 = np.array([[1, 2],
                 [0, 3]])

print(np.dot(arr1, arr2))

[[ 1  8]
 [ 4 23]]


## 절댓값

In [44]:
# np.abs()

arr1 = np.array([[1, -2],
                 [-4, 5]])

print(np.abs(arr1))

[[1 2]
 [4 5]]


## 올림, 내림, 반올림, 버림

In [49]:
arr1 = np.array([[1.932, -2.339],
                 [-4.145, 5.296]])


# np.ceil()로 올림 연산
print(np.ceil(arr1))


# np.floor()로 내림 연산
print(np.floor(arr1))


# np.round()로 반올림 연산
print(np.round(arr1))


# np.trunc()로 버림
print(np.trunc(arr1))

[[ 2. -2.]
 [-4.  6.]]
[[ 1. -3.]
 [-5.  5.]]
[[ 2. -2.]
 [-4.  5.]]
[[ 1. -2.]
 [-4.  5.]]


# 배열의 연산 - 3

## min(), max()

In [53]:
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

In [56]:
# np.min()
print(np.min(arr))
print(arr.min())

# np.max()
print(np.max(arr))
print(arr.max())

0
0
4
4


In [62]:
# axis 값 지정하기

print(arr.min(axis=0))     ## axis=0 은 열별 최소값 반환
print(arr.min(axis=1))     ## axis=1 은 행별 최소값 반환

print(arr.max(axis=0))     ## axis=0 은 열별 최대값 반환
print(arr.max(axis=1))     ## axis=1 은 행별 최대값 반환

[0 1 3]
[1 0]
[1 2 4]
[3 4]


## sum(), mean()

In [79]:
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

In [73]:
# np.sum()

print(np.sum(arr))
print(arr.sum())


# axis 지정

print(arr.sum(axis=0))
print(arr.sum(0))

print(arr.sum(axis=1))
print(arr.sum(1))

11
11
[1 3 7]
[1 3 7]
[6 5]
[6 5]


In [74]:
# np.mean()

print(np.mean(arr))
print(arr.mean())


# axis 지정

print(arr.mean(0))
print(arr.mean(1))

1.8333333333333333
1.8333333333333333
[0.5 1.5 3.5]
[2.         1.66666667]


## std(), cumsum()

In [80]:
arr = np.array([[1, 2, 3],
                [0, 1, 4]])

In [75]:
# np.std() --> 표준편차

print(np.std(arr))
print(arr.std())


# axis 지정

print(arr.std(0))
print(arr.std(1))

1.343709624716425
1.343709624716425
[0.5 0.5 0.5]
[0.81649658 1.69967317]


In [78]:
# np.cumsum() --> 누적값 계산 (cumulative sum)

print(np.cumsum(arr))
print(arr.cumsum())


# axis 지정

print(arr.cumsum(0))
print(arr.cumsum(1))

[ 1  3  6  6  7 11]
[ 1  3  6  6  7 11]
[[1 2 3]
 [1 3 7]]
[[1 3 6]
 [0 1 5]]


## median()

In [91]:
arr = np.array([[1, 2, 3],
                [0, 1, 4],
                [1, 5, 2]])

In [94]:
# np.median() --> 중앙값

print(np.median(arr))


# axis 지정

print(np.median(arr, axis=0))
print(np.median(arr, axis=1))

2.0
[1. 2. 3.]
[2. 1. 2.]


In [93]:
# 배열.median() 형태로 사용하면 오류가 난다!

print(arr.median())

AttributeError: 'numpy.ndarray' object has no attribute 'median'

# 배열의 연산 - 4

# 브로드캐스팅(Broadcasting)

In [2]:
# Shape이 다른 배열의 연산

# 벡터 연산의 장점