In [1]:
import numpy as np

# N차원 배열 생성

## N차원 배열 생성하기

In [3]:
# 1차원 배열
arr = np.array([1, 2, 3])
print(arr)

# 2차원 배열
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [6]:
# 리스트와는 다르다!

print(type([1, 2, 3]))
print(type(arr))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
# 리스트와 튜플을 사용한 배열 만들기

tpl = (4, 5, 6)
arr = np.array(tpl)
print(arr)

lst = [1, 2, 3]
arr = np.array(lst)
print(arr)

lst2 = [[1, 2, 3], [4, 5, 6]]
arr2 = np.array(lst2)
print(arr2)

[4 5 6]
[1 2 3]
[[1 2 3]
 [4 5 6]]


In [15]:
# shape

arr1 = np.array([1, 2, 3])
arr2 = np.array([[1, 2, 3], [4, 5, 6]])

print(arr1.shape, arr2.shape)

(3,) (2, 3)


In [17]:
# 차원 (ndim)

print(arr1.ndim)
print(arr2.ndim)

1
2


In [18]:
# size

print(arr1.size)
print(arr2.size)

3
6


## N차원 배열의 데이터 타입

### dtype으로 데이터 타입 저장하기

In [44]:
## float
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr, arr.dtype)

## int
arr = np.array([1.1, 2.2, 3.3], dtype=np.int64)
print(arr, arr.dtype)

## bool
arr = np.array([0, 1, 1], dtype=np.bool_)
print(arr, arr.dtype)

[1. 2. 3.] float64
[1 2 3] int64
[False  True  True] bool


### DeprecationWarning

In [31]:
# DeprecationWarning에 대해서 더 읽어보기!
## np.를 붙이지 않고 써도 된다는 것 같다...나중에 필요해지면 다시 읽어보자!

arr = np.array([1, 2, 3], dtype=np.float)
print(arr)

[1. 2. 3.]


C:\Users\ringp\AppData\Local\Temp/ipykernel_2748/1882518240.py:3: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  arr = np.array([1, 2, 3], dtype=np.float)


### astype()으로 데이터 타입 변경하기

In [45]:
arr = np.array([0, 1, 2, 3])
print(arr, arr.dtype)

arr = arr.astype(np.float32)
print(arr, arr.dtype)

[0 1 2 3] int32
[0. 1. 2. 3.] float32


### 데이터 타입이 혼재하는 경우

In [51]:
# int형과 float형이 섞여 있다면 float에 맞춰서 배열 생성

arr = np.array([1, 2, 3.4])
print(arr, arr.dtype)


# 문자열이 있는 경우 문자열에 맞춰서(유니코드 형식으로) 배열 생성

arr = np.array([1, 2, 3.4, '64'])
print(arr, arr.dtype)


# 숫자인 문자열이 유니코드 형식일 때 다른 데이터 타입으로 변경 가능!

arr = np.array([1, 2, 3.4, '64'], dtype=np.int64)
print(arr, arr.dtype)


# 숫자가 아닌 문자열을 int 타입으로 변결할 경우! --> 에러 발생

arr = np.array([1, 2, 3.4, '64', '문자열'], dtype=np.int64)
print(arr, arr.dtype)

[1.  2.  3.4] float64
['1' '2' '3.4' '64'] <U32
[ 1  2  3 64] int64


ValueError: invalid literal for int() with base 10: '문자열'

## 정해진 형식의 N차원 배열 생성하기

## 특정 범위의 값을 가지는 N차원 배열 생성하기

## 난수로 이루어진 N차원 배열 생성하기

## 시드(Seed)값을 통한 난수 생성 제어